// src/lib/regenerateLane.js — REGENLANE-1
//
// The block-and-regenerate lane. Every flagged prose unit gets ONE chance to
// be REGENERATED by the model under a deterministic verifier; otherwise it
// stays flagged. Nothing here ever regex-edits prose — MALFORMEDSENT-1 proved
// 78 sentences a detector can see and nothing can fix, and every prior attempt
// to repair prose with a substitution regex is exactly what produced the
// damage in the first place (root-cause trace 2026-08-15).
//
// One paragraph is the unit of work: the model rewrites the whole paragraph
// around the defect, and the verifier accepts the rewrite only when it keeps
// the same shape (one paragraph, sane length, quote balance no worse, no new
// proper nouns, no departed name reintroduced, not still flagged, no new
// cross-book duplicate, fewer or equal similes, and actually different).
// A rejected candidate leaves the paragraph untouched — the flag stands.
//
// No book specifics live here. Everything is derived from the manuscript.

import { stripModelControlTokens } from './modelLeakGuard.js';
import { countParagraphs } from './structureUtils.js';
import { scanMalformedSentences } from './malformedSentence.js';
import { scanDuplicateIntroductions } from './introGuard.js';
import {
  splitSentencesForDedupe,
  normalizeSentenceForDedupe,
  collectProperNouns,
  CROSS_DUPE_MIN_WORDS,
} from './crossChapterDedupe.js';
import { SIMILE_RX } from './simileRecast.js';
import { isNonfictionProject } from './projectType.js';

export const REGENLANE_VERSION = 'regen-lane-v1';

let _callAgent = null;
async function getCallAgent() {
  if (!_callAgent) {
    const mod = await import(/* @vite-ignore */ '@/lib/localLLM');
    _callAgent = mod.callAgent;
  }
  return _callAgent;
}

function escapeRx(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const collapseWs = (s) => String(s || '').replace(/\s+/g, ' ');

function paragraphsOf(text) {
  return String(text || '')
    .replace(/\r\n/g, '\n')
    .split(/\n{2,}/)
    .filter((p) => p.trim().length > 0);
}

function findParagraphIndex(paragraphs, needle, normalize = null) {
  if (!needle) return -1;
  const target = normalize ? normalize(needle) : needle;
  if (!target) return -1;
  for (let i = 0; i < paragraphs.length; i += 1) {
    const hay = normalize ? normalize(paragraphs[i]) : paragraphs[i];
    if (hay.includes(target)) return i;
  }
  return -1;
}

function countOccurrences(haystack, needle) {
  if (!needle) return 0;
  return String(haystack).split(needle).length - 1;
}

// Drop the first word of every sentence in `text` — sentence-initial words
// are exempt from the proper-noun check (any word can open a sentence).
function stripSentenceInitialWords(text) {
  return splitSentencesForDedupe(text)
    .map((s) => String(s || '').trim())
    .filter(Boolean)
    .map((s) => s.replace(/^[“"]?\s*\S+\s*/, ''))
    .join(' ');
}

/**
 * Collect regeneration targets: at most one per paragraph, first detector to
 * claim a paragraph wins, capped at `maxUnits`.
 *
 * Built-in detectors, in priority order: malformed sentences (dropped
 * subject / agreement / bare verb / name echo), duplicate self-introductions
 * (every self-intro after the first), departed cast acting in a sentence.
 * `extraDetectors` are `(text) => [{ kind, sentence, reason }]` functions for
 * later arcs (banned vocabulary, template families, fragments, arc restarts).
 *
 * @returns {Array<{kind, sentence, paragraphIndex, paragraph, reason}>}
 */
export function collectRegenTargets(text, opts = {}) {
  const {
    cast = [],
    departed = [],
    extraDetectors = [],
    maxUnits = 12,
  } = opts;
  const t = String(text || '');
  if (!t.trim()) return [];

  const paragraphs = paragraphsOf(t);
  const claimed = new Set();
  const targets = [];

  const tryAdd = (kind, sentence, paragraphIndex, reason) => {
    if (targets.length >= maxUnits) return false;
    if (paragraphIndex < 0 || claimed.has(paragraphIndex)) return false;
    claimed.add(paragraphIndex);
    targets.push({ kind, sentence, paragraphIndex, paragraph: paragraphs[paragraphIndex], reason });
    return true;
  };

  for (const f of scanMalformedSentences(t, cast)) {
    if (targets.length >= maxUnits) break;
    const idx = findParagraphIndex(paragraphs, f.sentence);
    tryAdd(f.kind, f.sentence, idx, f.kind);
  }

  for (const d of scanDuplicateIntroductions(t, cast)) {
    if (targets.length >= maxUnits) break;
    for (const excerpt of (d.excerpts || []).slice(1)) {
      if (targets.length >= maxUnits) break;
      const idx = findParagraphIndex(paragraphs, excerpt, collapseWs);
      tryAdd('duplicate-introduction', excerpt, idx, `${d.name} introduces themselves again (${d.count}x total)`);
    }
  }

  if (Array.isArray(departed) && departed.length) {
    const nameAlt = departed.filter(Boolean).map(escapeRx).join('|');
    if (nameAlt) {
      const rx = new RegExp(`^[“"'’]*\\s*(${nameAlt})\\b`);
      for (const raw of splitSentencesForDedupe(t)) {
        if (targets.length >= maxUnits) break;
        const s = String(raw || '').trim();
        if (!s) continue;
        const m = s.match(rx);
        if (!m) continue;
        const idx = findParagraphIndex(paragraphs, s);
        tryAdd('departed-active', s, idx, `${m[1]} appears active after departing`);
      }
    }
  }

  for (const det of (Array.isArray(extraDetectors) ? extraDetectors : [])) {
    if (targets.length >= maxUnits) break;
    let found = [];
    try { found = det(t) || []; } catch { found = []; }
    for (const f of found) {
      if (targets.length >= maxUnits) break;
      const sentence = f?.sentence || '';
      const idx = findParagraphIndex(paragraphs, sentence);
      tryAdd(f?.kind || 'custom', sentence, idx, f?.reason || f?.kind || 'custom');
    }
  }

  return targets;
}

/**
 * Deterministic verdict on a regenerated paragraph. ALL checks must pass.
 */
export function verifyRegeneratedParagraph(original, candidate, opts = {}) {
  const { cast = [], priorProse = [], departed = [], rescan = null } = opts;
  const orig = String(original || '');
  const cand = String(candidate || '').trim();
  if (!cand) return { ok: false, reason: 'empty' };

  // (1) exactly one paragraph.
  if (/\n{2,}/.test(cand)) return { ok: false, reason: 'paragraph-count' };

  // (2) length envelope.
  const ratio = cand.length / Math.max(1, orig.trim().length);
  if (ratio < 0.6 || ratio > 1.6) return { ok: false, reason: 'length-ratio' };

  // (3) smart-quote imbalance no worse than the original.
  const imbalance = (s) => {
    let open = 0; let close = 0;
    for (const ch of s) { if (ch === '“') open += 1; else if (ch === '”') close += 1; }
    return Math.abs(open - close);
  };
  if (imbalance(cand) > imbalance(orig)) return { ok: false, reason: 'quote-balance' };

  // (4) closed world: no new capitalized token beyond the original paragraph + cast.
  const allowedCaps = new Set([...collectProperNouns(orig), ...cast]);
  for (const tok of collectProperNouns(stripSentenceInitialWords(cand))) {
    if (!allowedCaps.has(tok)) return { ok: false, reason: `new-proper-noun:${tok}` };
  }

  // (5) the rewrite must not still trip any detector.
  if (typeof rescan === 'function') {
    let stillFlagged = [];
    try { stillFlagged = rescan(cand) || []; } catch { stillFlagged = []; }
    if (stillFlagged.length > 0) return { ok: false, reason: 'still-flagged' };
  }

  // (6) no 12+-word sentence duplicated from earlier prose.
  if (Array.isArray(priorProse) && priorProse.length) {
    const priorNorms = new Set();
    for (const p of priorProse) {
      for (const s of splitSentencesForDedupe(p)) {
        const norm = normalizeSentenceForDedupe(s);
        if (norm.split(' ').length >= CROSS_DUPE_MIN_WORDS) priorNorms.add(norm);
      }
    }
    for (const s of splitSentencesForDedupe(cand)) {
      const norm = normalizeSentenceForDedupe(s);
      if (norm.split(' ').length >= CROSS_DUPE_MIN_WORDS && priorNorms.has(norm)) {
        return { ok: false, reason: 'prior-duplicate' };
      }
    }
  }

  // (7) no more similes than the original had.
  const countSimiles = (s) => (String(s).match(SIMILE_RX) || []).length;
  if (countSimiles(cand) > countSimiles(orig)) return { ok: false, reason: 'simile-density' };

  // (8) a departed name may not be reintroduced.
  for (const name of (Array.isArray(departed) ? departed : [])) {
    if (!name) continue;
    const rx = new RegExp(`\\b${escapeRx(name)}\\b`);
    if (rx.test(cand) && !rx.test(orig)) return { ok: false, reason: 'departed-reintroduced' };
  }

  // (9) actually different.
  if (cand === orig.trim()) return { ok: false, reason: 'unchanged' };

  return { ok: true, reason: '' };
}

function cleanLLMParagraph(raw) {
  let s = typeof raw === 'string' ? raw : raw?.text || raw?.content || String(raw || '');
  s = stripModelControlTokens(s).text;
  s = s.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  s = s.replace(/^(?:here(?:'s| is)[^:]*:|rewritten paragraph:|paragraph:)\s*/i, '');
  s = s.replace(/^```[a-z]*\n?|\n?```$/g, '').trim();
  return s.trim();
}

const SYSTEM = [
  'You are line-editing ONE paragraph of a novel chapter. Rewrite the paragraph to fix exactly the defect named. Keep every event, name, object and fact. Keep dialogue quoted as it is unless the defect is inside it. Keep tense and point of view. Return exactly one paragraph, no commentary.',
].join('\n');

/**
 * Regenerate every flagged paragraph in `text`, one LLM call at a time.
 * Fiction only — nonfiction gets its lane in Arc G (closed-world verifier).
 *
 * @returns {{text, regenerated, skipped: Array<{kind, sentence, reason}>, targets}}
 */
export async function regenerateFlaggedParagraphs(text, opts = {}) {
  const {
    callLLM = null,
    project = null,
    cast = [],
    departed = [],
    priorProse = [],
    stateFacts = '',
    extraDetectors = [],
    maxUnits = 12,
    timeoutMs = 90000,
    label = 'text',
    onProgress = () => {},
  } = opts;

  const original = String(text || '');
  if (isNonfictionProject(project)) {
    return { text: original, regenerated: 0, skipped: [{ reason: 'nf-skip' }], targets: [] };
  }
  if (!original.trim()) return { text: original, regenerated: 0, skipped: [], targets: [] };

  const targets = collectRegenTargets(original, { cast, departed, extraDetectors, maxUnits });
  if (!targets.length) {
    console.log(`[REGENLANE] ${label}: targets 0, regenerated 0, skipped 0`);
    return { text: original, regenerated: 0, skipped: [], targets: [] };
  }

  const beforeParagraphs = countParagraphs(original);
  let out = original;

  const callOne = callLLM || (async (userPrompt, systemPrompt, maxTokens) => {
    const agent = await getCallAgent();
    return agent({ prompt: userPrompt, taskType: 'polish', project, temperature: 0.5, maxTokens, systemPromptOverride: systemPrompt });
  });

  const rescan = (candidateText) => collectRegenTargets(candidateText, { cast, departed, extraDetectors, maxUnits: 1 });

  const skipped = [];
  let regenerated = 0;

  // SEQUENTIAL — one LLM call at a time, always.
  for (const target of targets) {
    const { kind, sentence, paragraph } = target;
    if (!paragraph || countOccurrences(out, paragraph) !== 1) {
      skipped.push({ kind, sentence, reason: 'paragraph-not-unique' });
      continue;
    }
    onProgress(`Regen: rewriting a flagged paragraph (${label})…`);

    const userPrompt = `DEFECT (${kind}): "${sentence}"\nKNOWN CAST: ${cast.join(', ')}\n${stateFacts}\n\nPARAGRAPH:\n${paragraph}`;
    let raw = null;
    try {
      let timer = null;
      const timeout = new Promise((_, reject) => { timer = setTimeout(() => reject(new Error('timeout')), timeoutMs); });
      raw = await Promise.race([callOne(userPrompt, SYSTEM, 500), timeout]).finally(() => timer && clearTimeout(timer));
    } catch (err) {
      skipped.push({ kind, sentence, reason: `llm-error:${err?.message || 'unknown'}` });
      continue;
    }

    const candidate = cleanLLMParagraph(raw);
    const verdict = verifyRegeneratedParagraph(paragraph, candidate, { kind, cast, priorProse, departed, rescan });
    if (!verdict.ok) {
      console.warn(`[REGENLANE] rejected (${verdict.reason}): "${sentence.slice(0, 70)}"`);
      skipped.push({ kind, sentence, reason: verdict.reason });
      continue;
    }
    if (countOccurrences(out, paragraph) !== 1) {
      skipped.push({ kind, sentence, reason: 'paragraph-not-unique' });
      continue;
    }
    out = out.split(paragraph).join(candidate);
    regenerated += 1;
  }

  // TEST ONLY (regenlane1.acceptance.mjs): the verifier makes a genuine
  // paragraph-count drift unreachable through a normal accepted candidate
  // (rule 0.2/2's structural check already rejects multi-paragraph
  // candidates before they are ever applied) — this hook deterministically
  // exercises the revert branch below without weakening that guarantee.
  if (opts._forceParagraphMismatchForTest) out = out.replace(/\n{2,}/, '\n');

  const afterParagraphs = countParagraphs(out);
  if (afterParagraphs !== beforeParagraphs) {
    console.warn(`[REGENLANE] paragraph count changed (${beforeParagraphs} -> ${afterParagraphs}) — REVERTED`);
    return {
      text: original,
      regenerated: 0,
      skipped: targets.map((t) => ({ kind: t.kind, sentence: t.sentence, reason: 'lane-reverted' })),
      targets,
    };
  }

  console.log(`[REGENLANE] ${label}: targets ${targets.length}, regenerated ${regenerated}, skipped ${skipped.length}`);
  return { text: out, regenerated, skipped, targets };
}
