// src/lib/regenerateLane.js — REGENLANE-1
//
// The block-and-regenerate lane. Every flagged prose unit gets ONE chance to
// be REGENERATED by the model under a deterministic verifier; otherwise it
// stays flagged. Nothing here ever regex-edits prose — MALFORMEDSENT-1 proved
// 78 sentences a detector can see and nothing can fix, and every prior attempt
// to repair prose with a substitution regex is exactly what produced the
// damage in the first place (root-cause trace 2026-08-15).
//
// One paragraph is the unit of work: the model rewrites the whole paragraph
// around the defect, and the verifier accepts the rewrite only when it keeps
// the same shape (one paragraph, sane length, quote balance no worse, no new
// proper nouns, no departed name reintroduced, not still flagged, no new
// cross-book duplicate, fewer or equal similes, and actually different).
// A rejected candidate leaves the paragraph untouched — the flag stands.
//
// No book specifics live here. Everything is derived from the manuscript.

import { stripModelControlTokens } from './modelLeakGuard.js';
import { countParagraphs } from './structureUtils.js';
import { scanMalformedSentences } from './malformedSentence.js';
import { scanDuplicateIntroductions } from './introGuard.js';
import {
  splitSentencesForDedupe,
  normalizeSentenceForDedupe,
  collectProperNouns,
  CROSS_DUPE_MIN_WORDS,
  normalizeModelTypography,
} from './crossChapterDedupe.js';
import { SIMILE_RX } from './simileRecast.js';
import { isNonfictionProject } from './projectType.js';
import { closedWorldCheck, createInEV, buildEvidenceCorpus } from './closedWorldText.js'; // REGENLANE-2 / REGENLANE-2B

export const REGENLANE_VERSION = 'regen-lane-v2';

let _callAgent = null;
async function getCallAgent() {
  if (!_callAgent) {
    const mod = await import(/* @vite-ignore */ '@/lib/localLLM');
    _callAgent = mod.callAgent;
  }
  return _callAgent;
}

function escapeRx(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const collapseWs = (s) => String(s || '').replace(/\s+/g, ' ');

function paragraphsOf(text) {
  return String(text || '')
    .replace(/\r\n/g, '\n')
    .split(/\n{2,}/)
    .filter((p) => p.trim().length > 0);
}

function findParagraphIndex(paragraphs, needle, normalize = null) {
  if (!needle) return -1;
  const target = normalize ? normalize(needle) : needle;
  if (!target) return -1;
  for (let i = 0; i < paragraphs.length; i += 1) {
    const hay = normalize ? normalize(paragraphs[i]) : paragraphs[i];
    if (hay.includes(target)) return i;
  }
  return -1;
}

function countOccurrences(haystack, needle) {
  if (!needle) return 0;
  return String(haystack).split(needle).length - 1;
}

// Drop the first word of every sentence in `text` — sentence-initial words
// are exempt from the proper-noun check (any word can open a sentence).
function stripSentenceInitialWords(text) {
  return splitSentencesForDedupe(text)
    .map((s) => String(s || '').trim())
    .filter(Boolean)
    .map((s) => s.replace(/^[“"]?\s*\S+\s*/, ''))
    .join(' ');
}

/**
 * Collect regeneration targets: at most one per paragraph, first detector to
 * claim a paragraph wins, capped at `maxUnits`.
 *
 * Built-in detectors, in priority order: malformed sentences (dropped
 * subject / agreement / bare verb / name echo), duplicate self-introductions
 * (every self-intro after the first), departed cast acting in a sentence.
 * `extraDetectors` are `(text) => [{ kind, sentence, reason }]` functions for
 * later arcs (banned vocabulary, template families, fragments, arc restarts).
 *
 * REGENLANE-1D (finding 36): every detector above runs against the WHOLE
 * chapter text `t`, not the isolated paragraph — that is precisely why a
 * budget-based extraDetector (a template family, an opening echo) can fire
 * here at all: its budget is measured across the chapter, and a single
 * paragraph in isolation is never "over budget" on its own. Each target's
 * `defects`/`mustNotContain` must therefore come from THESE chapter-level
 * findings, grouped by which paragraph they landed in — never from a fresh
 * re-scan of the lone paragraph, which throws that chapter-wide context
 * away and silently ships `defects: []` for a target the chapter scan did
 * flag (live: a Ch.2 target's DEFECTS list was empty and only a name got
 * swapped; the actual defect — a template phrase — was never in the
 * prompt).
 *
 * @returns {Array<{kind, sentence, paragraphIndex, paragraph, reason, defects, mustNotContain}>}
 */
export function collectRegenTargets(text, opts = {}) {
  const {
    cast = [],
    departed = [],
    extraDetectors = [],
    maxUnits = 12,
  } = opts;
  const t = String(text || '');
  if (!t.trim()) return [];

  const paragraphs = paragraphsOf(t);
  const claimed = new Set();
  const targets = [];
  // Every finding any detector produced against the whole chapter,
  // regardless of which one (if any) went on to claim its paragraph —
  // grouped by paragraphIndex so a claimed paragraph's DEFECTS list carries
  // ALL of the chapter-level findings that landed inside it, not just the
  // claiming one.
  const findingsByParagraph = new Map();

  const recordFinding = (paragraphIndex, kind, sentence, reason, mustNotContain) => {
    if (paragraphIndex < 0) return;
    const list = Array.isArray(mustNotContain)
      ? mustNotContain.filter(Boolean)
      : (mustNotContain ? [mustNotContain] : (sentence ? [sentence] : []));
    if (!findingsByParagraph.has(paragraphIndex)) findingsByParagraph.set(paragraphIndex, []);
    const bucket = findingsByParagraph.get(paragraphIndex);
    const key = kind + '::' + reason;
    if (bucket.some((f) => (f.kind + '::' + f.reason) === key)) return;
    bucket.push({ kind, sentence, reason, mustNotContain: list });
  };

  const tryAdd = (kind, sentence, paragraphIndex, reason) => {
    if (targets.length >= maxUnits) return false;
    if (paragraphIndex < 0 || claimed.has(paragraphIndex)) return false;
    claimed.add(paragraphIndex);
    targets.push({ kind, sentence, paragraphIndex, paragraph: paragraphs[paragraphIndex], reason });
    return true;
  };

  for (const f of scanMalformedSentences(t, cast)) {
    const idx = findParagraphIndex(paragraphs, f.sentence);
    recordFinding(idx, f.kind, f.sentence, f.kind, f.sentence);
    tryAdd(f.kind, f.sentence, idx, f.kind);
  }

  for (const d of scanDuplicateIntroductions(t, cast)) {
    for (const excerpt of (d.excerpts || []).slice(1)) {
      const idx = findParagraphIndex(paragraphs, excerpt, collapseWs);
      const reason = `${d.name} introduces themselves again (${d.count}x total)`;
      recordFinding(idx, 'duplicate-introduction', excerpt, reason, excerpt);
      tryAdd('duplicate-introduction', excerpt, idx, reason);
    }
  }

  if (Array.isArray(departed) && departed.length) {
    const nameAlt = departed.filter(Boolean).map(escapeRx).join('|');
    if (nameAlt) {
      const rx = new RegExp(`^[“"'’]*\\s*(${nameAlt})\\b`);
      for (const raw of splitSentencesForDedupe(t)) {
        const s = String(raw || '').trim();
        if (!s) continue;
        const m = s.match(rx);
        if (!m) continue;
        const idx = findParagraphIndex(paragraphs, s);
        const reason = `${m[1]} appears active after departing`;
        recordFinding(idx, 'departed-active', s, reason, s);
        tryAdd('departed-active', s, idx, reason);
      }
    }
  }

  for (const det of (Array.isArray(extraDetectors) ? extraDetectors : [])) {
    let found = [];
    try { found = det(t) || []; } catch { found = []; }
    for (const f of found) {
      const sentence = f?.sentence || '';
      const idx = findParagraphIndex(paragraphs, sentence);
      const kind = f?.kind || 'custom';
      const reason = f?.reason || f?.kind || 'custom';
      recordFinding(idx, kind, sentence, reason, f?.mustNotContain || sentence);
      tryAdd(kind, sentence, idx, reason);
    }
  }

  for (const target of targets) {
    const defects = findingsByParagraph.get(target.paragraphIndex)
      || [{ kind: target.kind, sentence: target.sentence, reason: target.reason, mustNotContain: target.sentence ? [target.sentence] : [] }];
    target.defects = defects;
    target.mustNotContain = [...new Set(defects.flatMap((d) => d.mustNotContain))];
  }

  return targets;
}

// REGENLANE-1D (finding 38): cardinal number words the model might invent as
// a fabricated fact ("thirty-seven beats per minute"). Ordinals ("second",
// "third") are deliberately excluded — they show up constantly in ordinary
// idiom ("a second later") and are not the failure mode finding 38 targets.
const NUMBER_WORDS = [
  'zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine',
  'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen',
  'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety',
  'hundred', 'thousand', 'million', 'billion',
];
const NUMBER_WORD_RX = new RegExp(`\\b(?:${NUMBER_WORDS.join('|')})(?:-(?:${NUMBER_WORDS.join('|')}))?\\b`, 'gi');

function collectNumberTokens(s) {
  const text = String(s || '');
  const digits = text.match(/\d+/g) || [];
  const words = (text.match(NUMBER_WORD_RX) || []).map((w) => w.toLowerCase());
  return new Set([...digits, ...words]);
}

/**
 * Deterministic verdict on a regenerated paragraph. ALL checks must pass.
 */
export function verifyRegeneratedParagraph(original, candidate, opts = {}) {
  const { cast = [], priorProse = [], departed = [], rescan = null, mustNotContain = [], project = null } = opts;
  const orig = String(original || '');
  const cand = String(candidate || '').trim();
  if (!cand) return { ok: false, reason: 'empty' };

  // (1) exactly one paragraph.
  if (/\n{2,}/.test(cand)) return { ok: false, reason: 'paragraph-count' };

  // (2) length envelope. REGENLANE-1C: a short original (a template-phrase
  // fragment like "Indifferent." or "For now, it had to be.") cannot be
  // replaced with a concrete, specific detail inside 0.6-1.6x of a dozen
  // characters — live, this rejected every short-paragraph regeneration
  // outright. Originals under 120 chars get a wider ratio window (0.5-3.0x)
  // OR an absolute +100-char allowance, whichever passes; longer originals
  // keep the tight 0.6-1.6x ratio.
  const origLen = orig.trim().length;
  const ratio = cand.length / Math.max(1, origLen);
  // The +100-char allowance widens the UPPER bound only (rescuing a short
  // template phrase expanded into a full concrete sentence) — it must never
  // let a short original be gutted down to almost nothing, so the 0.5x
  // floor still applies either way.
  const ratioOk = origLen < 120
    ? (ratio >= 0.5 && (ratio <= 3.0 || cand.length <= origLen + 100))
    : (ratio >= 0.6 && ratio <= 1.6);
  // REGENLANE-1D (finding 38): log the actual ratio on a length-ratio
  // rejection — 27 live rejections looked like the model answering with
  // one sentence instead of the whole paragraph, and there was no way to
  // tell from the log alone.
  if (!ratioOk) return { ok: false, reason: 'length-ratio', ratio: Number(ratio.toFixed(2)) };

  // (3) smart-quote imbalance no worse than the original.
  const imbalance = (s) => {
    let open = 0; let close = 0;
    for (const ch of s) { if (ch === '“') open += 1; else if (ch === '”') close += 1; }
    return Math.abs(open - close);
  };
  if (imbalance(cand) > imbalance(orig)) return { ok: false, reason: 'quote-balance' };

  // (3b) REGENLANE-1C typography guard: live, accepted candidates introduced
  // a straight quote the original never had (curly '’' -> straight "'") and
  // a space jammed inside a smart quote ("“ Coolant circulating,”") — the
  // export gate's "mixed straight and curly" hard block and the typographic
  // scrub exist because of exactly this class of damage.
  const straightQuoteCount = (s) => (String(s).match(/['"]/g) || []).length;
  if (straightQuoteCount(cand) > straightQuoteCount(orig)) return { ok: false, reason: 'typography' };
  if (/“\s/.test(cand) || /\s”/.test(cand)) return { ok: false, reason: 'typography' };

  // (3c) a departed name may not be reintroduced — checked before the
  // closed-world checks below so a departed cast member coming back gets
  // the specific, actionable "departed-reintroduced" reason rather than
  // being lumped in with an ordinary new-proper-noun/cast violation.
  for (const name of (Array.isArray(departed) ? departed : [])) {
    if (!name) continue;
    const rx = new RegExp(`\\b${escapeRx(name)}\\b`);
    if (rx.test(cand) && !rx.test(orig)) return { ok: false, reason: 'departed-reintroduced' };
  }

  // (4) closed world: candidate proper nouns must be a SUBSET of the
  // original paragraph's own — REGENLANE-1C tightened this from "original +
  // cast", which let the model swap one cast member's name for another's
  // (Rodge -> Roderick, live) since both were in the allowed set.
  // REGENLANE-2B (finding 45): for NF, a proper noun the ORIGINAL paragraph
  // didn't have is still legitimate when the RESEARCH has it — check (10)
  // below is the real closed-world judge; check (4) alone was rejecting
  // real, evidence-backed historical terms (Galveston, Congress, Union...)
  // on every NF rewrite. Fiction is unchanged (nfInEV stays null).
  const allowedCaps = new Set(collectProperNouns(orig));
  const nfInEV = isNonfictionProject(project) ? createInEV(buildEvidenceCorpus(project)) : null;
  for (const tok of collectProperNouns(stripSentenceInitialWords(cand))) {
    if (allowedCaps.has(tok)) continue;
    if (nfInEV && nfInEV(tok)) continue;
    return { ok: false, reason: `new-proper-noun:${tok}` };
  }
  // (4b) REGENLANE-1D (finding 37): a cast name (or its possessive) counts
  // wherever it sits, sentence-initial included — the sentence-initial
  // exemption above exists so an ordinary word opening a sentence isn't
  // mistaken for a proper noun, but a cast member's own name is never
  // ambiguous that way. Live: "Zin looked at him..." -> "Zinnia looked at
  // him..." was ACCEPTED because "Zinnia" opened its sentence and got
  // stripped from scrutiny; the candidate's cast names must be a subset of
  // the ORIGINAL paragraph's own cast names present, full stop.
  const castLower = new Set((Array.isArray(cast) ? cast : []).filter(Boolean).map((n) => String(n).toLowerCase()));
  if (castLower.size) {
    const origCastPresent = new Set(collectProperNouns(orig).filter((tok) => castLower.has(tok.toLowerCase())));
    for (const tok of collectProperNouns(cand)) {
      if (!castLower.has(tok.toLowerCase())) continue;
      if (!origCastPresent.has(tok)) return { ok: false, reason: `new-proper-noun:${tok}` };
    }
  }
  // (4c) REGENLANE-1D (finding 38): no new fact — a digit sequence or a
  // cardinal number word the original paragraph didn't have. Live: an
  // accepted rewrite invented "thirty-seven beats per minute, the same
  // rhythm her grandmother had counted during her final days" — a fact with
  // no source anywhere in the paragraph.
  const origNumbers = collectNumberTokens(orig);
  for (const num of collectNumberTokens(cand)) {
    if (!origNumbers.has(num)) return { ok: false, reason: `new-number:${num}` };
  }

  // (4d) REGENLANE-1C defect-remains: none of the specific content that
  // trips a defect in this paragraph (a template key, an opening-echo gram,
  // a banned word, or the flagged sentence itself for the malformed kinds)
  // may still be present verbatim. Rescan (5) below runs the detectors
  // fresh on the lone candidate — invisible to a template hit now under the
  // per-paragraph chapter budget, or an echo gram, since a single paragraph
  // is never "over budget" on its own. Live: "Zin looked at him, really
  // looked at him..." was ACCEPTED after the model only swapped
  // Rodge -> Roderick and kept "really looked" — rescan never saw it because
  // one occurrence of a chapter-budget-1 family isn't over budget in
  // isolation; this check catches the literal phrase directly.
  for (const needle of (Array.isArray(mustNotContain) ? mustNotContain : [])) {
    if (!needle) continue;
    if (cand.toLowerCase().includes(String(needle).toLowerCase())) return { ok: false, reason: 'defect-remains' };
  }

  // (5) the rewrite must not still trip any detector.
  if (typeof rescan === 'function') {
    let stillFlagged = [];
    try { stillFlagged = rescan(cand) || []; } catch { stillFlagged = []; }
    if (stillFlagged.length > 0) return { ok: false, reason: 'still-flagged' };
  }

  // (6) no 12+-word sentence duplicated from earlier prose.
  if (Array.isArray(priorProse) && priorProse.length) {
    const priorNorms = new Set();
    for (const p of priorProse) {
      for (const s of splitSentencesForDedupe(p)) {
        const norm = normalizeSentenceForDedupe(s);
        if (norm.split(' ').length >= CROSS_DUPE_MIN_WORDS) priorNorms.add(norm);
      }
    }
    for (const s of splitSentencesForDedupe(cand)) {
      const norm = normalizeSentenceForDedupe(s);
      if (norm.split(' ').length >= CROSS_DUPE_MIN_WORDS && priorNorms.has(norm)) {
        return { ok: false, reason: 'prior-duplicate' };
      }
    }
  }

  // (7) no more similes than the original had.
  const countSimiles = (s) => (String(s).match(SIMILE_RX) || []).length;
  if (countSimiles(cand) > countSimiles(orig)) return { ok: false, reason: 'simile-density' };

  // (9) actually different.
  if (cand === orig.trim()) return { ok: false, reason: 'unchanged' };

  // (10) REGENLANE-2: for NF projects, the candidate may introduce no
  // closed-world violation the original did not already have — an
  // un-evidenced proper noun, date, or number smuggled in during the
  // "fix the defect" rewrite is exactly the fabrication ARCH-1B exists to
  // catch, and the lane must not ship one just because it fixed something
  // else. A violation the ORIGINAL already carried is not new — the lane
  // regenerates a flagged paragraph without being asked to also fact-check
  // pre-existing prose.
  if (isNonfictionProject(project)) {
    // Diff by ATOM, not by sentence snippet — the candidate sentence is
    // never byte-identical to the original by construction, so a
    // snippet-only diff would treat every pre-existing violation as "new"
    // on every single rewrite.
    const origAtoms = new Set(closedWorldCheck(orig, project).map((v) => v.atom));
    const newViolations = closedWorldCheck(cand, project).filter((v) => !origAtoms.has(v.atom));
    if (newViolations.length) return { ok: false, reason: 'closed-world' };
  }

  return { ok: true, reason: '' };
}

function cleanLLMParagraph(raw) {
  let s = typeof raw === 'string' ? raw : raw?.text || raw?.content || String(raw || '');
  s = stripModelControlTokens(s).text;
  s = s.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  s = s.replace(/^(?:here(?:'s| is)[^:]*:|rewritten paragraph:|paragraph:)\s*/i, '');
  s = s.replace(/^```[a-z]*\n?|\n?```$/g, '').trim();
  s = s.trim();
  // REGENLANE-1D (finding 38): normalize the model's own typography to the
  // manuscript's smart-quote convention BEFORE the verifier's typography
  // guard ever sees it — cleanup of model output, not a prose edit.
  s = normalizeModelTypography(s);
  return s;
}

const SYSTEM = [
  'You are line-editing ONE paragraph of a novel chapter. Rewrite the paragraph to fix EVERY defect listed below — a rewrite that fixes only one and leaves another is not acceptable. Return the COMPLETE paragraph, start to finish — never a single sentence, a fragment, or an excerpt. Keep every event, name, object and fact exactly as given; do not add any fact, number, name, backstory detail, or event that is not already in the paragraph. Keep dialogue quoted as it is unless a defect is inside it. Keep tense and point of view. Return exactly one paragraph, no commentary.',
].join('\n');

/**
 * Regenerate every flagged paragraph in `text`, one LLM call at a time.
 * Fiction and nonfiction alike — REGENLANE-2 added the NF closed-world
 * verifier check (10), so nonfiction no longer needs a separate skip.
 *
 * @returns {{text, regenerated, skipped: Array<{kind, sentence, reason}>, targets}}
 */
export async function regenerateFlaggedParagraphs(text, opts = {}) {
  const {
    callLLM = null,
    project = null,
    cast = [],
    departed = [],
    priorProse = [],
    stateFacts = '',
    extraDetectors = [],
    maxUnits = 12,
    timeoutMs = 90000,
    label = 'text',
    onProgress = () => {},
  } = opts;

  const original = String(text || '');
  if (!original.trim()) return { text: original, regenerated: 0, skipped: [], targets: [], replacements: [] };

  const targets = collectRegenTargets(original, { cast, departed, extraDetectors, maxUnits });
  if (!targets.length) {
    console.log(`[REGENLANE] ${label}: targets 0, regenerated 0, skipped 0`);
    return { text: original, regenerated: 0, skipped: [], targets: [], replacements: [] };
  }

  const beforeParagraphs = countParagraphs(original);
  let out = original;

  const callOne = callLLM || (async (userPrompt, systemPrompt, maxTokens) => {
    const agent = await getCallAgent();
    return agent({ prompt: userPrompt, taskType: 'polish', project, temperature: 0.5, maxTokens, systemPromptOverride: systemPrompt });
  });

  const rescan = (candidateText) => collectRegenTargets(candidateText, { cast, departed, extraDetectors, maxUnits: 1 });

  const skipped = [];
  // REGENLANE-2B: every accepted replacement, so a caller (NFGUARD-1) can
  // revert everything ELSE it did to a chapter and re-apply only these —
  // each one already closed-world-verified by check (10) when NF.
  const replacements = [];
  let regenerated = 0;

  // SEQUENTIAL — one LLM call at a time, always.
  for (const target of targets) {
    const { kind, sentence, paragraph, defects, mustNotContain } = target;
    if (!paragraph || countOccurrences(out, paragraph) !== 1) {
      skipped.push({ kind, sentence, reason: 'paragraph-not-unique' });
      continue;
    }
    onProgress(`Regen: rewriting a flagged paragraph (${label})…`);

    // REGENLANE-1C: every defect this paragraph carries, numbered — not
    // just the one that happened to claim the paragraph first. A candidate
    // that fixes the claiming defect but leaves a second one untouched
    // still ships wrong; the model needs to see all of them.
    const defectsList = (Array.isArray(defects) && defects.length) ? defects : [{ kind, sentence, reason: kind }];
    const defectsBlock = defectsList.map((d, i) => `${i + 1}. ${d.reason}`).join('\n');
    const userPrompt = `DEFECTS:\n${defectsBlock}\nKNOWN CAST: ${cast.join(', ')}\n${stateFacts}\n\nPARAGRAPH:\n${paragraph}`;
    let raw = null;
    try {
      let timer = null;
      const timeout = new Promise((_, reject) => { timer = setTimeout(() => reject(new Error('timeout')), timeoutMs); });
      raw = await Promise.race([callOne(userPrompt, SYSTEM, 500), timeout]).finally(() => timer && clearTimeout(timer));
    } catch (err) {
      skipped.push({ kind, sentence, reason: `llm-error:${err?.message || 'unknown'}` });
      continue;
    }

    const candidate = cleanLLMParagraph(raw);
    const verdict = verifyRegeneratedParagraph(paragraph, candidate, { kind, cast, priorProse, departed, rescan, mustNotContain, project });
    if (!verdict.ok) {
      const detail = verdict.ratio != null ? ` ratio=${verdict.ratio}` : '';
      console.warn(`[REGENLANE] rejected (${verdict.reason}${detail}): "${sentence.slice(0, 70)}"`);
      skipped.push({ kind, sentence, reason: verdict.reason });
      continue;
    }
    if (countOccurrences(out, paragraph) !== 1) {
      skipped.push({ kind, sentence, reason: 'paragraph-not-unique' });
      continue;
    }
    out = out.split(paragraph).join(candidate);
    regenerated += 1;
    replacements.push({ paragraphIndex: target.paragraphIndex, before: paragraph, after: candidate });
  }

  // TEST ONLY (regenlane1.acceptance.mjs): the verifier makes a genuine
  // paragraph-count drift unreachable through a normal accepted candidate
  // (rule 0.2/2's structural check already rejects multi-paragraph
  // candidates before they are ever applied) — this hook deterministically
  // exercises the revert branch below without weakening that guarantee.
  if (opts._forceParagraphMismatchForTest) out = out.replace(/\n{2,}/, '\n');

  const afterParagraphs = countParagraphs(out);
  if (afterParagraphs !== beforeParagraphs) {
    console.warn(`[REGENLANE] paragraph count changed (${beforeParagraphs} -> ${afterParagraphs}) — REVERTED`);
    return {
      text: original,
      regenerated: 0,
      skipped: targets.map((t) => ({ kind: t.kind, sentence: t.sentence, reason: 'lane-reverted' })),
      targets,
      replacements: [],
    };
  }

  console.log(`[REGENLANE] ${label}: targets ${targets.length}, regenerated ${regenerated}, skipped ${skipped.length}`);
  return { text: out, regenerated, skipped, targets, replacements };
}
