// src/lib/regenerateLane.js — REGENLANE-1
//
// The block-and-regenerate lane. Every flagged prose unit gets ONE chance to
// be REGENERATED by the model under a deterministic verifier; otherwise it
// stays flagged. Nothing here ever regex-edits prose — MALFORMEDSENT-1 proved
// 78 sentences a detector can see and nothing can fix, and every prior attempt
// to repair prose with a substitution regex is exactly what produced the
// damage in the first place (root-cause trace 2026-08-15).
//
// One paragraph is the unit of work: the model rewrites the whole paragraph
// around the defect, and the verifier accepts the rewrite only when it keeps
// the same shape (one paragraph, sane length, quote balance no worse, no new
// proper nouns, no departed name reintroduced, not still flagged, no new
// cross-book duplicate, fewer or equal similes, and actually different).
// A rejected candidate leaves the paragraph untouched — the flag stands.
//
// No book specifics live here. Everything is derived from the manuscript.

import { stripModelControlTokens } from './modelLeakGuard.js';
import { countParagraphs } from './structureUtils.js';
import { scanMalformedSentences } from './malformedSentence.js';
import { scanDuplicateIntroductions } from './introGuard.js';
import {
  splitSentencesForDedupe,
  normalizeSentenceForDedupe,
  collectProperNouns,
  CROSS_DUPE_MIN_WORDS,
} from './crossChapterDedupe.js';
import { SIMILE_RX } from './simileRecast.js';
import { isNonfictionProject } from './projectType.js';

export const REGENLANE_VERSION = 'regen-lane-v1';

let _callAgent = null;
async function getCallAgent() {
  if (!_callAgent) {
    const mod = await import(/* @vite-ignore */ '@/lib/localLLM');
    _callAgent = mod.callAgent;
  }
  return _callAgent;
}

function escapeRx(s) {
  return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const collapseWs = (s) => String(s || '').replace(/\s+/g, ' ');

function paragraphsOf(text) {
  return String(text || '')
    .replace(/\r\n/g, '\n')
    .split(/\n{2,}/)
    .filter((p) => p.trim().length > 0);
}

function findParagraphIndex(paragraphs, needle, normalize = null) {
  if (!needle) return -1;
  const target = normalize ? normalize(needle) : needle;
  if (!target) return -1;
  for (let i = 0; i < paragraphs.length; i += 1) {
    const hay = normalize ? normalize(paragraphs[i]) : paragraphs[i];
    if (hay.includes(target)) return i;
  }
  return -1;
}

function countOccurrences(haystack, needle) {
  if (!needle) return 0;
  return String(haystack).split(needle).length - 1;
}

// Drop the first word of every sentence in `text` — sentence-initial words
// are exempt from the proper-noun check (any word can open a sentence).
function stripSentenceInitialWords(text) {
  return splitSentencesForDedupe(text)
    .map((s) => String(s || '').trim())
    .filter(Boolean)
    .map((s) => s.replace(/^[“"]?\s*\S+\s*/, ''))
    .join(' ');
}

// REGENLANE-1C: every defect the built-in detectors + extraDetectors find
// inside ONE paragraph, with no one-per-paragraph exclusivity — unlike
// collectRegenTargets, which lets only the first detector to claim a
// paragraph report anything. Two uses: (a) the lane prompt names every
// defect in the paragraph, not just the one that happened to claim it
// first (finding 27); (b) each defect's `mustNotContain` becomes part of
// the verifier's defect-remains check (finding 28) — the specific template
// key / echo gram / banned word a detector supplies, or the flagged
// sentence verbatim when a detector doesn't supply anything narrower
// (true for the malformed-sentence kinds, which ARE the sentence-level
// defect).
function collectAllDefectsInParagraph(paragraph, opts = {}) {
  const { cast = [], departed = [], extraDetectors = [] } = opts;
  const p = String(paragraph || '');
  const findings = [];
  const push = (kind, sentence, reason, mustNotContain) => {
    const list = Array.isArray(mustNotContain)
      ? mustNotContain.filter(Boolean)
      : (mustNotContain ? [mustNotContain] : (sentence ? [sentence] : []));
    findings.push({ kind, sentence, reason, mustNotContain: list });
  };

  for (const f of scanMalformedSentences(p, cast)) push(f.kind, f.sentence, f.kind, f.sentence);

  for (const d of scanDuplicateIntroductions(p, cast)) {
    for (const excerpt of (d.excerpts || []).slice(1)) {
      push('duplicate-introduction', excerpt, `${d.name} introduces themselves again (${d.count}x total)`, excerpt);
    }
  }

  if (Array.isArray(departed) && departed.length) {
    const nameAlt = departed.filter(Boolean).map(escapeRx).join('|');
    if (nameAlt) {
      const rx = new RegExp(`^[“"'’]*\\s*(${nameAlt})\\b`);
      for (const raw of splitSentencesForDedupe(p)) {
        const s = String(raw || '').trim();
        if (!s) continue;
        const m = s.match(rx);
        if (m) push('departed-active', s, `${m[1]} appears active after departing`, s);
      }
    }
  }

  for (const det of (Array.isArray(extraDetectors) ? extraDetectors : [])) {
    let found = [];
    try { found = det(p) || []; } catch { found = []; }
    for (const f of found) {
      push(f?.kind || 'custom', f?.sentence || '', f?.reason || f?.kind || 'custom', f?.mustNotContain || f?.sentence);
    }
  }

  const seen = new Set();
  return findings.filter((f) => {
    const key = f.kind + '::' + f.reason;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

/**
 * Collect regeneration targets: at most one per paragraph, first detector to
 * claim a paragraph wins, capped at `maxUnits`.
 *
 * Built-in detectors, in priority order: malformed sentences (dropped
 * subject / agreement / bare verb / name echo), duplicate self-introductions
 * (every self-intro after the first), departed cast acting in a sentence.
 * `extraDetectors` are `(text) => [{ kind, sentence, reason }]` functions for
 * later arcs (banned vocabulary, template families, fragments, arc restarts).
 *
 * @returns {Array<{kind, sentence, paragraphIndex, paragraph, reason, defects, mustNotContain}>}
 */
export function collectRegenTargets(text, opts = {}) {
  const {
    cast = [],
    departed = [],
    extraDetectors = [],
    maxUnits = 12,
  } = opts;
  const t = String(text || '');
  if (!t.trim()) return [];

  const paragraphs = paragraphsOf(t);
  const claimed = new Set();
  const targets = [];

  const tryAdd = (kind, sentence, paragraphIndex, reason) => {
    if (targets.length >= maxUnits) return false;
    if (paragraphIndex < 0 || claimed.has(paragraphIndex)) return false;
    claimed.add(paragraphIndex);
    const paragraph = paragraphs[paragraphIndex];
    // REGENLANE-1C: every defect in this paragraph, not just the one that
    // claimed it — feeds the prompt's DEFECTS list and the verifier's
    // mustNotContain check.
    const defects = collectAllDefectsInParagraph(paragraph, { cast, departed, extraDetectors });
    const mustNotContain = [...new Set(defects.flatMap((d) => d.mustNotContain))];
    targets.push({ kind, sentence, paragraphIndex, paragraph, reason, defects, mustNotContain });
    return true;
  };

  for (const f of scanMalformedSentences(t, cast)) {
    if (targets.length >= maxUnits) break;
    const idx = findParagraphIndex(paragraphs, f.sentence);
    tryAdd(f.kind, f.sentence, idx, f.kind);
  }

  for (const d of scanDuplicateIntroductions(t, cast)) {
    if (targets.length >= maxUnits) break;
    for (const excerpt of (d.excerpts || []).slice(1)) {
      if (targets.length >= maxUnits) break;
      const idx = findParagraphIndex(paragraphs, excerpt, collapseWs);
      tryAdd('duplicate-introduction', excerpt, idx, `${d.name} introduces themselves again (${d.count}x total)`);
    }
  }

  if (Array.isArray(departed) && departed.length) {
    const nameAlt = departed.filter(Boolean).map(escapeRx).join('|');
    if (nameAlt) {
      const rx = new RegExp(`^[“"'’]*\\s*(${nameAlt})\\b`);
      for (const raw of splitSentencesForDedupe(t)) {
        if (targets.length >= maxUnits) break;
        const s = String(raw || '').trim();
        if (!s) continue;
        const m = s.match(rx);
        if (!m) continue;
        const idx = findParagraphIndex(paragraphs, s);
        tryAdd('departed-active', s, idx, `${m[1]} appears active after departing`);
      }
    }
  }

  for (const det of (Array.isArray(extraDetectors) ? extraDetectors : [])) {
    if (targets.length >= maxUnits) break;
    let found = [];
    try { found = det(t) || []; } catch { found = []; }
    for (const f of found) {
      if (targets.length >= maxUnits) break;
      const sentence = f?.sentence || '';
      const idx = findParagraphIndex(paragraphs, sentence);
      tryAdd(f?.kind || 'custom', sentence, idx, f?.reason || f?.kind || 'custom');
    }
  }

  return targets;
}

/**
 * Deterministic verdict on a regenerated paragraph. ALL checks must pass.
 */
export function verifyRegeneratedParagraph(original, candidate, opts = {}) {
  const { priorProse = [], departed = [], rescan = null, mustNotContain = [] } = opts;
  const orig = String(original || '');
  const cand = String(candidate || '').trim();
  if (!cand) return { ok: false, reason: 'empty' };

  // (1) exactly one paragraph.
  if (/\n{2,}/.test(cand)) return { ok: false, reason: 'paragraph-count' };

  // (2) length envelope. REGENLANE-1C: a short original (a template-phrase
  // fragment like "Indifferent." or "For now, it had to be.") cannot be
  // replaced with a concrete, specific detail inside 0.6-1.6x of a dozen
  // characters — live, this rejected every short-paragraph regeneration
  // outright. Originals under 120 chars get a wider ratio window (0.5-3.0x)
  // OR an absolute +100-char allowance, whichever passes; longer originals
  // keep the tight 0.6-1.6x ratio.
  const origLen = orig.trim().length;
  const ratio = cand.length / Math.max(1, origLen);
  // The +100-char allowance widens the UPPER bound only (rescuing a short
  // template phrase expanded into a full concrete sentence) — it must never
  // let a short original be gutted down to almost nothing, so the 0.5x
  // floor still applies either way.
  const ratioOk = origLen < 120
    ? (ratio >= 0.5 && (ratio <= 3.0 || cand.length <= origLen + 100))
    : (ratio >= 0.6 && ratio <= 1.6);
  if (!ratioOk) return { ok: false, reason: 'length-ratio' };

  // (3) smart-quote imbalance no worse than the original.
  const imbalance = (s) => {
    let open = 0; let close = 0;
    for (const ch of s) { if (ch === '“') open += 1; else if (ch === '”') close += 1; }
    return Math.abs(open - close);
  };
  if (imbalance(cand) > imbalance(orig)) return { ok: false, reason: 'quote-balance' };

  // (3b) REGENLANE-1C typography guard: live, accepted candidates introduced
  // a straight quote the original never had (curly '’' -> straight "'") and
  // a space jammed inside a smart quote ("“ Coolant circulating,”") — the
  // export gate's "mixed straight and curly" hard block and the typographic
  // scrub exist because of exactly this class of damage.
  const straightQuoteCount = (s) => (String(s).match(/['"]/g) || []).length;
  if (straightQuoteCount(cand) > straightQuoteCount(orig)) return { ok: false, reason: 'typography' };
  if (/“\s/.test(cand) || /\s”/.test(cand)) return { ok: false, reason: 'typography' };

  // (4) closed world: candidate proper nouns must be a SUBSET of the
  // original paragraph's own — REGENLANE-1C tightened this from "original +
  // cast", which let the model swap one cast member's name for another's
  // (Rodge -> Roderick, live) since both were in the allowed set.
  const allowedCaps = new Set(collectProperNouns(orig));
  for (const tok of collectProperNouns(stripSentenceInitialWords(cand))) {
    if (!allowedCaps.has(tok)) return { ok: false, reason: `new-proper-noun:${tok}` };
  }

  // (4b) REGENLANE-1C defect-remains: none of the specific content that
  // trips a defect in this paragraph (a template key, an opening-echo gram,
  // a banned word, or the flagged sentence itself for the malformed kinds)
  // may still be present verbatim. Rescan (5) below runs the detectors
  // fresh on the lone candidate — invisible to a template hit now under the
  // per-paragraph chapter budget, or an echo gram, since a single paragraph
  // is never "over budget" on its own. Live: "Zin looked at him, really
  // looked at him..." was ACCEPTED after the model only swapped
  // Rodge -> Roderick and kept "really looked" — rescan never saw it because
  // one occurrence of a chapter-budget-1 family isn't over budget in
  // isolation; this check catches the literal phrase directly.
  for (const needle of (Array.isArray(mustNotContain) ? mustNotContain : [])) {
    if (!needle) continue;
    if (cand.toLowerCase().includes(String(needle).toLowerCase())) return { ok: false, reason: 'defect-remains' };
  }

  // (5) the rewrite must not still trip any detector.
  if (typeof rescan === 'function') {
    let stillFlagged = [];
    try { stillFlagged = rescan(cand) || []; } catch { stillFlagged = []; }
    if (stillFlagged.length > 0) return { ok: false, reason: 'still-flagged' };
  }

  // (6) no 12+-word sentence duplicated from earlier prose.
  if (Array.isArray(priorProse) && priorProse.length) {
    const priorNorms = new Set();
    for (const p of priorProse) {
      for (const s of splitSentencesForDedupe(p)) {
        const norm = normalizeSentenceForDedupe(s);
        if (norm.split(' ').length >= CROSS_DUPE_MIN_WORDS) priorNorms.add(norm);
      }
    }
    for (const s of splitSentencesForDedupe(cand)) {
      const norm = normalizeSentenceForDedupe(s);
      if (norm.split(' ').length >= CROSS_DUPE_MIN_WORDS && priorNorms.has(norm)) {
        return { ok: false, reason: 'prior-duplicate' };
      }
    }
  }

  // (7) no more similes than the original had.
  const countSimiles = (s) => (String(s).match(SIMILE_RX) || []).length;
  if (countSimiles(cand) > countSimiles(orig)) return { ok: false, reason: 'simile-density' };

  // (8) a departed name may not be reintroduced.
  for (const name of (Array.isArray(departed) ? departed : [])) {
    if (!name) continue;
    const rx = new RegExp(`\\b${escapeRx(name)}\\b`);
    if (rx.test(cand) && !rx.test(orig)) return { ok: false, reason: 'departed-reintroduced' };
  }

  // (9) actually different.
  if (cand === orig.trim()) return { ok: false, reason: 'unchanged' };

  return { ok: true, reason: '' };
}

function cleanLLMParagraph(raw) {
  let s = typeof raw === 'string' ? raw : raw?.text || raw?.content || String(raw || '');
  s = stripModelControlTokens(s).text;
  s = s.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  s = s.replace(/^(?:here(?:'s| is)[^:]*:|rewritten paragraph:|paragraph:)\s*/i, '');
  s = s.replace(/^```[a-z]*\n?|\n?```$/g, '').trim();
  return s.trim();
}

const SYSTEM = [
  'You are line-editing ONE paragraph of a novel chapter. Rewrite the paragraph to fix EVERY defect listed below — a rewrite that fixes only one and leaves another is not acceptable. Keep every event, name, object and fact. Keep dialogue quoted as it is unless a defect is inside it. Keep tense and point of view. Return exactly one paragraph, no commentary.',
].join('\n');

/**
 * Regenerate every flagged paragraph in `text`, one LLM call at a time.
 * Fiction only — nonfiction gets its lane in Arc G (closed-world verifier).
 *
 * @returns {{text, regenerated, skipped: Array<{kind, sentence, reason}>, targets}}
 */
export async function regenerateFlaggedParagraphs(text, opts = {}) {
  const {
    callLLM = null,
    project = null,
    cast = [],
    departed = [],
    priorProse = [],
    stateFacts = '',
    extraDetectors = [],
    maxUnits = 12,
    timeoutMs = 90000,
    label = 'text',
    onProgress = () => {},
  } = opts;

  const original = String(text || '');
  if (isNonfictionProject(project)) {
    return { text: original, regenerated: 0, skipped: [{ reason: 'nf-skip' }], targets: [] };
  }
  if (!original.trim()) return { text: original, regenerated: 0, skipped: [], targets: [] };

  const targets = collectRegenTargets(original, { cast, departed, extraDetectors, maxUnits });
  if (!targets.length) {
    console.log(`[REGENLANE] ${label}: targets 0, regenerated 0, skipped 0`);
    return { text: original, regenerated: 0, skipped: [], targets: [] };
  }

  const beforeParagraphs = countParagraphs(original);
  let out = original;

  const callOne = callLLM || (async (userPrompt, systemPrompt, maxTokens) => {
    const agent = await getCallAgent();
    return agent({ prompt: userPrompt, taskType: 'polish', project, temperature: 0.5, maxTokens, systemPromptOverride: systemPrompt });
  });

  const rescan = (candidateText) => collectRegenTargets(candidateText, { cast, departed, extraDetectors, maxUnits: 1 });

  const skipped = [];
  let regenerated = 0;

  // SEQUENTIAL — one LLM call at a time, always.
  for (const target of targets) {
    const { kind, sentence, paragraph, defects, mustNotContain } = target;
    if (!paragraph || countOccurrences(out, paragraph) !== 1) {
      skipped.push({ kind, sentence, reason: 'paragraph-not-unique' });
      continue;
    }
    onProgress(`Regen: rewriting a flagged paragraph (${label})…`);

    // REGENLANE-1C: every defect this paragraph carries, numbered — not
    // just the one that happened to claim the paragraph first. A candidate
    // that fixes the claiming defect but leaves a second one untouched
    // still ships wrong; the model needs to see all of them.
    const defectsList = (Array.isArray(defects) && defects.length) ? defects : [{ kind, sentence, reason: kind }];
    const defectsBlock = defectsList.map((d, i) => `${i + 1}. ${d.reason}`).join('\n');
    const userPrompt = `DEFECTS:\n${defectsBlock}\nKNOWN CAST: ${cast.join(', ')}\n${stateFacts}\n\nPARAGRAPH:\n${paragraph}`;
    let raw = null;
    try {
      let timer = null;
      const timeout = new Promise((_, reject) => { timer = setTimeout(() => reject(new Error('timeout')), timeoutMs); });
      raw = await Promise.race([callOne(userPrompt, SYSTEM, 500), timeout]).finally(() => timer && clearTimeout(timer));
    } catch (err) {
      skipped.push({ kind, sentence, reason: `llm-error:${err?.message || 'unknown'}` });
      continue;
    }

    const candidate = cleanLLMParagraph(raw);
    const verdict = verifyRegeneratedParagraph(paragraph, candidate, { kind, priorProse, departed, rescan, mustNotContain });
    if (!verdict.ok) {
      console.warn(`[REGENLANE] rejected (${verdict.reason}): "${sentence.slice(0, 70)}"`);
      skipped.push({ kind, sentence, reason: verdict.reason });
      continue;
    }
    if (countOccurrences(out, paragraph) !== 1) {
      skipped.push({ kind, sentence, reason: 'paragraph-not-unique' });
      continue;
    }
    out = out.split(paragraph).join(candidate);
    regenerated += 1;
  }

  // TEST ONLY (regenlane1.acceptance.mjs): the verifier makes a genuine
  // paragraph-count drift unreachable through a normal accepted candidate
  // (rule 0.2/2's structural check already rejects multi-paragraph
  // candidates before they are ever applied) — this hook deterministically
  // exercises the revert branch below without weakening that guarantee.
  if (opts._forceParagraphMismatchForTest) out = out.replace(/\n{2,}/, '\n');

  const afterParagraphs = countParagraphs(out);
  if (afterParagraphs !== beforeParagraphs) {
    console.warn(`[REGENLANE] paragraph count changed (${beforeParagraphs} -> ${afterParagraphs}) — REVERTED`);
    return {
      text: original,
      regenerated: 0,
      skipped: targets.map((t) => ({ kind: t.kind, sentence: t.sentence, reason: 'lane-reverted' })),
      targets,
    };
  }

  console.log(`[REGENLANE] ${label}: targets ${targets.length}, regenerated ${regenerated}, skipped ${skipped.length}`);
  return { text: out, regenerated, skipped, targets };
}
