// Theme presets based on Orca PublishSettings + Buckram defaults + McLuhan overrides.
// Each preset is a complete BookTheme object. Users pick one then override fields.

const BASE = {
  bleed: false,
  textAlign: 'justify',
  hyphens: true,
  orphans: 2,
  widows: 2,
  suppressFirstPageHeader: true,
  rectoHeader: 'bookTitle',
  versoHeader: 'chapterTitle',
  pageNumberPosition: 'footer-center',
  sections: { halfTitle: true, titlePage: true, copyright: true, dedication: false, epigraph: false, toc: true, aboutAuthor: false },
  dedicationText: '',
  epigraphText: '',
  aboutAuthorText: '',
};

export const BOOK_THEME_PRESETS = {
  classicNovel: {
    ...BASE,
    id: 'classicNovel',
    label: 'Classic Novel',
    trimSize: '6x9',
    margins: { top: 0.75, bottom: 0.75, inside: 0.85, outside: 0.65 },
    bodyFont: 'Cormorant Garamond',
    headingFont: 'Cormorant Garamond',
    bodySize: 11,
    headingSize: 22,
    lineHeight: 1.55,
    paragraphStyle: 'indented',
    indentSize: 0.22,
    chapterNumberFormat: 'word',
    chapterTitleAlign: 'center',
    dropCapEnabled: true,
    dropCapLines: 3,
    dropCapFont: 'Cormorant Garamond',
    leadInStyle: 'smallcaps',
    sceneBreak: '⁂',
    headerFont: 'Inter',
    headerSize: 9,
  },
  mcluhan: {
    ...BASE,
    id: 'mcluhan',
    label: 'McLuhan (Pressbooks)',
    trimSize: '6x9',
    margins: { top: 0.75, bottom: 0.75, inside: 0.85, outside: 0.65 },
    bodyFont: 'Lora',
    headingFont: 'Cormorant Garamond',
    bodySize: 11,
    headingSize: 24,
    lineHeight: 1.5,
    paragraphStyle: 'indented',
    indentSize: 0.2,
    chapterNumberFormat: 'word',
    chapterTitleAlign: 'center',
    dropCapEnabled: true,
    dropCapLines: 3,
    dropCapFont: 'Cormorant Garamond',
    leadInStyle: 'smallcaps',
    sceneBreak: '⁂',
    headerFont: 'Lora',
    headerSize: 9,
    sections: { ...BASE.sections, halfTitle: true, dedication: true },
  },
  modernClean: {
    ...BASE,
    id: 'modernClean',
    label: 'Modern Clean',
    trimSize: '6x9',
    margins: { top: 0.7, bottom: 0.7, inside: 0.8, outside: 0.65 },
    bodyFont: 'Inter',
    headingFont: 'Inter',
    bodySize: 11,
    headingSize: 20,
    lineHeight: 1.6,
    paragraphStyle: 'block',
    indentSize: 0,
    chapterNumberFormat: 'numeric',
    chapterTitleAlign: 'left',
    dropCapEnabled: false,
    dropCapLines: 0,
    dropCapFont: 'Inter',
    leadInStyle: 'none',
    sceneBreak: '• • •',
    headerFont: 'Inter',
    headerSize: 9,
    sections: { ...BASE.sections, halfTitle: false, aboutAuthor: true },
  },
  paperbackThriller: {
    ...BASE,
    id: 'paperbackThriller',
    label: 'Paperback Thriller',
    trimSize: '5x8',
    margins: { top: 0.7, bottom: 0.7, inside: 0.8, outside: 0.6 },
    bodyFont: 'Inter',
    headingFont: 'Inter',
    bodySize: 10.5,
    headingSize: 18,
    lineHeight: 1.45,
    paragraphStyle: 'indented',
    indentSize: 0.18,
    chapterNumberFormat: 'numeric',
    chapterTitleAlign: 'center',
    dropCapEnabled: false,
    dropCapLines: 0,
    dropCapFont: 'Inter',
    leadInStyle: 'italics',
    sceneBreak: '***',
    headerFont: 'Inter',
    headerSize: 8,
    pageNumberPosition: 'footer-right',
    sections: { ...BASE.sections, toc: false, aboutAuthor: true },
  },
  literarySerif: {
    ...BASE,
    id: 'literarySerif',
    label: 'Literary Serif',
    trimSize: '5.5x8.5',
    margins: { top: 0.85, bottom: 0.85, inside: 0.9, outside: 0.7 },
    bodyFont: 'Cormorant Garamond',
    headingFont: 'Cormorant Garamond',
    bodySize: 11.5,
    headingSize: 24,
    lineHeight: 1.7,
    paragraphStyle: 'indented',
    indentSize: 0.24,
    chapterNumberFormat: 'none',
    chapterTitleAlign: 'center',
    dropCapEnabled: true,
    dropCapLines: 4,
    dropCapFont: 'Cormorant Garamond',
    leadInStyle: 'smallcaps',
    sceneBreak: '✦',
    headerFont: 'Cormorant Garamond',
    headerSize: 9,
    sections: { ...BASE.sections, halfTitle: true, dedication: true, epigraph: true, toc: false, aboutAuthor: true },
  },
  academic: {
    ...BASE,
    id: 'academic',
    label: 'Academic',
    trimSize: '7x10',
    margins: { top: 0.9, bottom: 0.9, inside: 1, outside: 0.8 },
    bodyFont: 'Inter',
    headingFont: 'Inter',
    bodySize: 11,
    headingSize: 18,
    lineHeight: 1.7,
    paragraphStyle: 'block',
    indentSize: 0,
    chapterNumberFormat: 'numeric',
    chapterTitleAlign: 'left',
    dropCapEnabled: false,
    dropCapLines: 0,
    dropCapFont: 'Inter',
    leadInStyle: 'none',
    sceneBreak: '• • •',
    headerFont: 'Inter',
    headerSize: 9,
    suppressFirstPageHeader: false,
    sections: { ...BASE.sections, halfTitle: false, aboutAuthor: true },
  },
  largePrint: {
    ...BASE,
    id: 'largePrint',
    label: 'Large Print',
    trimSize: '6x9',
    margins: { top: 0.8, bottom: 0.8, inside: 0.85, outside: 0.7 },
    bodyFont: 'Inter',
    headingFont: 'Inter',
    bodySize: 14,
    headingSize: 24,
    lineHeight: 1.8,
    paragraphStyle: 'block',
    indentSize: 0,
    chapterNumberFormat: 'numeric',
    chapterTitleAlign: 'center',
    dropCapEnabled: false,
    dropCapLines: 0,
    dropCapFont: 'Inter',
    leadInStyle: 'none',
    sceneBreak: '• • •',
    headerFont: 'Inter',
    headerSize: 10,
    hyphens: false,
    textAlign: 'left',
    sections: { ...BASE.sections, halfTitle: false },
  },
  manuscript: {
    ...BASE,
    id: 'manuscript',
    label: 'Manuscript (Submission)',
    trimSize: '8.5x11',
    margins: { top: 1, bottom: 1, inside: 1, outside: 1 },
    bodyFont: 'Times New Roman',
    headingFont: 'Times New Roman',
    bodySize: 12,
    headingSize: 14,
    lineHeight: 2,
    paragraphStyle: 'indented',
    indentSize: 0.5,
    chapterNumberFormat: 'numeric',
    chapterTitleAlign: 'center',
    dropCapEnabled: false,
    dropCapLines: 0,
    dropCapFont: 'Times New Roman',
    leadInStyle: 'none',
    sceneBreak: '#',
    headerFont: 'Times New Roman',
    headerSize: 10,
    pageNumberPosition: 'header-right',
    suppressFirstPageHeader: false,
    textAlign: 'left',
    hyphens: false,
    sections: { halfTitle: false, titlePage: true, copyright: false, dedication: false, epigraph: false, toc: false, aboutAuthor: false },
  },
  romance: {
    ...BASE,
    id: 'romance',
    label: 'Romance',
    trimSize: '5.5x8.5',
    margins: { top: 0.8, bottom: 0.8, inside: 0.85, outside: 0.7 },
    bodyFont: 'Cormorant Garamond',
    headingFont: 'Cormorant Garamond',
    bodySize: 11.5,
    headingSize: 22,
    lineHeight: 1.65,
    paragraphStyle: 'indented',
    indentSize: 0.22,
    chapterNumberFormat: 'word',
    chapterTitleAlign: 'center',
    dropCapEnabled: true,
    dropCapLines: 3,
    dropCapFont: 'Cormorant Garamond',
    leadInStyle: 'italics',
    sceneBreak: '♥',
    headerFont: 'Cormorant Garamond',
    headerSize: 9,
    sections: { ...BASE.sections, halfTitle: true, dedication: true, epigraph: true, toc: false, aboutAuthor: true },
  },
};

export function getDefaultBookTheme() {
  return { ...BOOK_THEME_PRESETS.classicNovel };
}

export function getBookTheme(projectTheme) {
  const defaults = getDefaultBookTheme();
  return {
    ...defaults,
    ...(projectTheme || {}),
    margins: { ...defaults.margins, ...(projectTheme?.margins || {}) },
    sections: { ...defaults.sections, ...(projectTheme?.sections || {}) },
  };
}