import assert from 'node:assert/strict';
import {generateChapterSummary,generateAndSaveSummary} from '../src/lib/chapterCohesion.js';
globalThis.__summaryTestCalls=[];
globalThis.__summaryTestSaves=[];
const beginning='BEGIN_STATE_MARKER\n';
const ending='\nFINAL_STATE_MARKER: the brace is reinforced, but the housing remains cracked.';
const body=beginning+'A scene paragraph. '.repeat(1900)+ending;
assert(body.length>12000 && body.length<64000);
await generateAndSaveSummary('fixture-chapter',body,14);
assert.equal(globalThis.__summaryTestCalls.length,1);
const prompt=globalThis.__summaryTestCalls[0].prompt;
assert(prompt.includes(body),'Regression: summarizer must receive the entire chapter, including its ending beyond 12,000 characters');
assert(prompt.includes(beginning)&&prompt.includes(ending));
const saved=JSON.parse(globalThis.__summaryTestSaves[0].fields.summary_json);
assert.equal(saved.physical_state,'FINAL_STATE_MARKER','Closing state reaches saved summary');
await generateChapterSummary('Short complete chapter. FINAL_STATE_MARKER',2);
assert(globalThis.__summaryTestCalls[1].prompt.includes('Short complete chapter. FINAL_STATE_MARKER'));
const count=globalThis.__summaryTestCalls.length;
await assert.rejects(generateChapterSummary('x'.repeat(64001),1),e=>e.code==='CHAPTER_SUMMARY_INPUT_TOO_LARGE');
await assert.rejects(generateChapterSummary('',1),/non-empty string/);
assert.equal(globalThis.__summaryTestCalls.length,count,'Rejected inputs must not call the model');
console.log('PASS: full long chapter, closing-state persistence, short chapter, explicit oversize rejection, empty input rejection, no network calls.');
